# 真实分布式FL测试 - 服务端配置 (星型拓扑)

use_gpu: False
seed: 2023
backend: 'torch'

# 基本FL设置
federate:
  client_num: 3
  mode: 'distributed'
  total_round_num: 2  # 短期测试，只训练2轮
  make_global_eval: False
  sample_client_num: 3
  method: 'FedAvg'

# 分布式设置
distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  role: 'server'
  data_idx: 0

# 网络拓扑构建 (核心测试功能!)
topology:
  use: True
  type: 'star'  # 星型拓扑: Client1-Client2-Client3
  timeout: 45.0
  max_connection_attempts: 3
  connection_retry_delay: 1.0
  require_full_topology: True
  save_construction_log: True
  log_dir: 'topology_logs'
  verbose: True

# 训练器设置
trainer:
  type: 'general'

# 评估设置
eval:
  freq: 10
  split: ['test']

# 数据设置
data:
  type: 'toy'
  
# 模型设置
model:
  type: 'lr'
  
# 优化器设置
train:
  optimizer:
    lr: 0.01
    type: 'SGD'
  local_update_steps: 1

# 输出设置
outdir: 'real_topology_test_exp'
expname: 'real_star_topology_test'
verbose: 1