# 实际分布式FL测试 - 服务端配置 (带拓扑构建)

use_gpu: False
seed: 12345

# 基本FL设置
federate:
  client_num: 3
  mode: 'distributed'
  total_round_num: 3  # 短期测试，只训练3轮
  make_global_eval: False
  sample_client_num: 3
  method: 'FedAvg'

# 分布式设置
distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  role: 'server'
  data_idx: 0

# 网络拓扑构建 (新功能测试!)
topology:
  use: True
  type: 'star'  # 测试星型拓扑: 1-2-3, Client2连接1和3
  timeout: 30.0
  max_connection_attempts: 3
  connection_retry_delay: 1.0
  require_full_topology: True
  save_construction_log: True
  log_dir: 'topology_logs'
  verbose: True

# 训练器设置
trainer:
  type: 'general'

# 评估设置
eval:
  freq: 10
  split: ['test']

# 数据设置
data:
  type: 'toy'

# 模型设置
model:
  type: 'lr'
  
# 优化器设置
train:
  optimizer:
    lr: 0.01
    type: 'SGD'
  local_update_steps: 1

# 输出设置
outdir: 'topology_test_exp'
expname: 'topology_star_test'