bittorrent:
  chunk_selection: rarest_first
  enable: true
  min_completion_ratio: 0.8
  timeout: 600.0
  verbose: true
chunk:
  importance_method: snip
  num_chunks: 10
chunk_importance_method: snip
chunk_num: 10
criterion:
  type: CrossEntropyLoss
data:
  args:
  - download: true
  num_workers: 0
  root: data/
  splits:
  - 0.8
  - 0.1
  - 0.1
  splitter: lda
  splitter_args:
  - alpha: 0.1
  test_transform:
  - - ToTensor
  - - Normalize
    - mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.247
      - 0.2435
      - 0.2616
  transform:
  - - ToTensor
  - - Normalize
    - mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.247
      - 0.2435
      - 0.2616
  type: CIFAR10@torchvision
dataloader:
  batch_size: 32
device: 0
distribute:
  client_host: 172.24.158.88
  client_port: 44729
  data_idx: 10
  role: client
  server_host: 172.24.158.88
  server_port: 42519
  use: true
eval:
  best_res_update_round_wise_key: test_acc
  freq: 1
  metrics:
  - acc
  - correct
federate:
  client_num: 10
  mode: distributed
  sample_client_num: 10
  total_round_num: 10
grad:
  grad_clip: 5.0
model:
  dropout: 0.0
  hidden: 512
  out_channels: 10
  type: convnet2
outdir: ray_v2_output/client_10_output
seed: 12355
topology:
  timeout: 600.0
  type: star
  use: true
  verbose: true
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    lr: 0.01
    type: SGD
    weight_decay: 0.0001
trainer:
  type: cvtrainer
use_gpu: true
