bittorrent:
  chunk_selection: rarest_first
  enable: true
  min_completion_ratio: 0.8
  timeout: 600.0
  verbose: true
chunk:
  importance_method: snip
  num_chunks: 10
chunk_importance_method: snip
chunk_num: 10
criterion:
  type: character_loss
data:
  root: data/
  splits:
  - 0.6
  - 0.2
  - 0.2
  splitter: lda
  splitter_args:
  - alpha: 0.5
  subsample: 0.5
  type: shakespeare
dataloader:
  batch_size: 8
device: 0
distribute:
  client_host: 127.0.0.1
  client_port: 50052
  data_idx: 0
  role: server
  server_host: 0.0.0.0|172.24.158.88|50265
  server_port: 50051
  use: true
eval:
  best_res_update_round_wise_key: test_acc
  freq: 1
  metrics:
  - acc
  - correct
federate:
  client_num: 2
  mode: distributed
  sample_client_num: 2
  total_round_num: 20
grad:
  grad_clip: 1.0
model:
  dropout: 0.1
  embed_size: 8
  hidden: 256
  in_channels: 80
  out_channels: 80
  type: lstm
outdir: ray_v2_output/server_output
seed: 12345
topology:
  connections: 2
  timeout: 600.0
  type: random
  use: true
  verbose: true
train:
  batch_or_epoch: epoch
  local_update_steps: 5
  optimizer:
    lr: 0.001
    type: Adam
    weight_decay: 0.0001
trainer:
  type: nlptrainer
use_gpu: false
