# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC_comm_manager.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gRPC_comm_manager.proto\"n\n\x0eMessageRequest\x12%\n\x03msg\x18\x01 \x03(\x0b\x32\x18.MessageRequest.MsgEntry\x1a\x35\n\x08MsgEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.MsgValue:\x02\x38\x01\"\xac\x01\n\x08MsgValue\x12\x1e\n\nsingle_msg\x18\x01 \x01(\x0b\x32\x08.mSingleH\x00\x12\x1a\n\x08list_msg\x18\x02 \x01(\x0b\x32\x06.mListH\x00\x12\x30\n\x12\x64ict_msg_stringkey\x18\x03 \x01(\x0b\x32\x12.mDict_keyIsStringH\x00\x12*\n\x0f\x64ict_msg_intkey\x18\x04 \x01(\x0b\x32\x0f.mDict_keyIsIntH\x00\x42\x06\n\x04type\"R\n\x07mSingle\x12\x15\n\x0b\x66loat_value\x18\x01 \x01(\x02H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x13\n\tstr_value\x18\x03 \x01(\tH\x00\x42\x06\n\x04type\"&\n\x05mList\x12\x1d\n\nlist_value\x18\x01 \x03(\x0b\x32\t.MsgValue\"\x87\x01\n\x11mDict_keyIsString\x12\x35\n\ndict_value\x18\x01 \x03(\x0b\x32!.mDict_keyIsString.DictValueEntry\x1a;\n\x0e\x44ictValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.MsgValue:\x02\x38\x01\"\x81\x01\n\x0emDict_keyIsInt\x12\x32\n\ndict_value\x18\x01 \x03(\x0b\x32\x1e.mDict_keyIsInt.DictValueEntry\x1a;\n\x0e\x44ictValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.MsgValue:\x02\x38\x01\"\x1e\n\x0fMessageResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2F\n\x10gRPCComServeFunc\x12\x32\n\x0bsendMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_comm_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST_MSGENTRY']._options = None
  _globals['_MESSAGEREQUEST_MSGENTRY']._serialized_options = b'8\001'
  _globals['_MDICT_KEYISSTRING_DICTVALUEENTRY']._options = None
  _globals['_MDICT_KEYISSTRING_DICTVALUEENTRY']._serialized_options = b'8\001'
  _globals['_MDICT_KEYISINT_DICTVALUEENTRY']._options = None
  _globals['_MDICT_KEYISINT_DICTVALUEENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGEREQUEST']._serialized_start=27
  _globals['_MESSAGEREQUEST']._serialized_end=137
  _globals['_MESSAGEREQUEST_MSGENTRY']._serialized_start=84
  _globals['_MESSAGEREQUEST_MSGENTRY']._serialized_end=137
  _globals['_MSGVALUE']._serialized_start=140
  _globals['_MSGVALUE']._serialized_end=312
  _globals['_MSINGLE']._serialized_start=314
  _globals['_MSINGLE']._serialized_end=396
  _globals['_MLIST']._serialized_start=398
  _globals['_MLIST']._serialized_end=436
  _globals['_MDICT_KEYISSTRING']._serialized_start=439
  _globals['_MDICT_KEYISSTRING']._serialized_end=574
  _globals['_MDICT_KEYISSTRING_DICTVALUEENTRY']._serialized_start=515
  _globals['_MDICT_KEYISSTRING_DICTVALUEENTRY']._serialized_end=574
  _globals['_MDICT_KEYISINT']._serialized_start=577
  _globals['_MDICT_KEYISINT']._serialized_end=706
  _globals['_MDICT_KEYISINT_DICTVALUEENTRY']._serialized_start=647
  _globals['_MDICT_KEYISINT_DICTVALUEENTRY']._serialized_end=706
  _globals['_MESSAGERESPONSE']._serialized_start=708
  _globals['_MESSAGERESPONSE']._serialized_end=738
  _globals['_GRPCCOMSERVEFUNC']._serialized_start=740
  _globals['_GRPCCOMSERVEFUNC']._serialized_end=810
# @@protoc_insertion_point(module_scope)
