# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from federatedscope.core.proto import gRPC_comm_manager_pb2 as federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in federatedscope/core/proto/gRPC_comm_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class gRPCComServeFuncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendMessage = channel.unary_unary(
                '/gRPCComServeFunc/sendMessage',
                request_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.MessageRequest.SerializeToString,
                response_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.streamChunks = channel.stream_stream(
                '/gRPCComServeFunc/streamChunks',
                request_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamRequest.SerializeToString,
                response_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamResponse.FromString,
                _registered_method=True)
        self.downloadChunks = channel.unary_stream(
                '/gRPCComServeFunc/downloadChunks',
                request_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkBatchRequest.SerializeToString,
                response_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamResponse.FromString,
                _registered_method=True)
        self.uploadChunks = channel.stream_unary(
                '/gRPCComServeFunc/uploadChunks',
                request_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamRequest.SerializeToString,
                response_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkBatchResponse.FromString,
                _registered_method=True)


class gRPCComServeFuncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendMessage(self, request, context):
        """🚀 原有的Unary RPC (兼容性)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamChunks(self, request_iterator, context):
        """🚀 新增：双向流式RPC用于chunk传输
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def downloadChunks(self, request, context):
        """🚀 新增：服务端流式RPC用于批量chunk下载
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadChunks(self, request_iterator, context):
        """🚀 新增：客户端流式RPC用于批量chunk上传  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCComServeFuncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.MessageRequest.FromString,
                    response_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.MessageResponse.SerializeToString,
            ),
            'streamChunks': grpc.stream_stream_rpc_method_handler(
                    servicer.streamChunks,
                    request_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamRequest.FromString,
                    response_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamResponse.SerializeToString,
            ),
            'downloadChunks': grpc.unary_stream_rpc_method_handler(
                    servicer.downloadChunks,
                    request_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkBatchRequest.FromString,
                    response_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamResponse.SerializeToString,
            ),
            'uploadChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadChunks,
                    request_deserializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamRequest.FromString,
                    response_serializer=federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gRPCComServeFunc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gRPCComServeFunc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class gRPCComServeFunc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gRPCComServeFunc/sendMessage',
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.MessageRequest.SerializeToString,
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gRPCComServeFunc/streamChunks',
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamRequest.SerializeToString,
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def downloadChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gRPCComServeFunc/downloadChunks',
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkBatchRequest.SerializeToString,
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def uploadChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gRPCComServeFunc/uploadChunks',
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkStreamRequest.SerializeToString,
            federatedscope_dot_core_dot_proto_dot_gRPC__comm__manager__pb2.ChunkBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
