# FederatedScope Docker edge device simulation configuration
# Using Docker containers to simulate different types of edge devices for federated learning

# Basic federated learning configuration
federate:
  mode: 'distributed'
  client_num: 5
  total_round_num: 10
  sample_client_num: 5

# Docker simulation configuration
docker_simulation:
  # Enable Docker simulation
  use_docker: True
  
  # Docker network configuration
  network_name: "fl_edge_network"
  enable_network_simulation: True
  
  # Device configuration - simulating real edge environment
  device_configs:
    - device_id: "client_1"
      device_type: "smartphone_high"
      docker_image: "federatedscope:smartphone-high"
      resources:
        memory: "4g"
        cpus: "4.0"
        gpu_support: True
      network_profile:
        bandwidth_up_kbps: 50000    # 5G network
        bandwidth_down_kbps: 100000
        latency_ms: 15
        packet_loss_rate: 0.001
        
    - device_id: "client_2"
      device_type: "smartphone_low"
      docker_image: "federatedscope:smartphone-low"
      resources:
        memory: "1.5g"
        cpus: "2.0"
        gpu_support: False
      network_profile:
        bandwidth_up_kbps: 10000    # 4G network
        bandwidth_down_kbps: 30000
        latency_ms: 40
        packet_loss_rate: 0.01
        
    - device_id: "client_3"
      device_type: "raspberry_pi"
      docker_image: "federatedscope:raspberry-pi"
      resources:
        memory: "4g"
        cpus: "4.0"
        gpu_support: False
      network_profile:
        bandwidth_up_kbps: 25000    # WiFi connection
        bandwidth_down_kbps: 50000
        latency_ms: 25
        packet_loss_rate: 0.005
        
    - device_id: "client_4"
      device_type: "iot_minimal"
      docker_image: "federatedscope:iot-minimal"
      resources:
        memory: "256m"
        cpus: "1.0"
        gpu_support: False
      network_profile:
        bandwidth_up_kbps: 128      # Low bandwidth IoT
        bandwidth_down_kbps: 512
        latency_ms: 200
        packet_loss_rate: 0.05
        
    - device_id: "server"
      device_type: "edge_server"
      docker_image: "federatedscope:edge-server"
      resources:
        memory: "16g"
        cpus: "8.0"
        gpu_support: True
      network_profile:
        bandwidth_up_kbps: 1000000  # Gigabit network
        bandwidth_down_kbps: 1000000
        latency_ms: 5
        packet_loss_rate: 0.0001

# Data configuration
data:
  root: 'data/'
  type: 'CIFAR10'
  splits: [0.6, 0.2, 0.2]
  
# Model configuration
model:
  type: 'convnet2'
  hidden: 2048
  dropout: 0.5

# Training configuration
train:
  optimizer:
    lr: 0.01
    weight_decay: 0.0001
  local_update_steps: 5
  batch_size: 32
  
# Evaluation configuration
eval:
  freq: 1
  metrics: ['acc', 'loss']
  
# Logging and output
output:
  use_tensorboard: True
  tensorboard:
    save_path: 'exp_out/docker_simulation/tensorboard'
  results:
    save_path: 'exp_out/docker_simulation/results'
    
# Other configuration
use_gpu: False  # Will be determined by Docker container internally
early_stop:
  patience: 10
  delta: 0.0