use_gpu: False
device: 0
seed: 12345

federate:
  client_num: 3
  mode: 'distributed'
  total_round_num: 5
  sample_client_num: 3

distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  role: 'server'
  data_idx: 0

data:
  type: 'toy'
  sizes: [10, 5]

model:
  type: 'lr'
  input_shape: [10]

train:
  local_update_steps: 2
  optimizer:
    lr: 0.01
    type: SGD

criterion:
  type: MSELoss

topology:
  use: True
  type: 'star'
  timeout: 60.0
  verbose: True

bittorrent:
  enable: True
  timeout: 60.0
  verbose: True
  chunk_selection: 'rarest_first'
  min_completion_ratio: 0.8

outdir: 'multi_process_test_v2/server_output'
